services:

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # REVISAR SI ES NECESARIO ports
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    container_name: ${WEB_CONTAINER_NAME}
    image: ${WEB_IMAGE}
    depends_on:
      - db
    ports:
      # Redireccionamiento de puertos
      - ${WEB_PORT}:8069
      - ${WEB_LONGPOLLING_PORT}:8072
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all

  # Database management in a single PHP file.
  # Comprobaremos si se crean las bases de datos
  web-db-management:
    container_name: ${WEB_DB_MANAGEMENT_CONTAINER_NAME}
    image: ${WEB_DB_MANAGEMENT_IMAGE}
    restart: always
    ports:
      - ${WEB_DB_MANAGEMENT_PORT}:8080

volumes:
  postgres-data:
  odoo-data:
